management:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ms
    username: root
    password: 20041220qQ#
  redis:
    host: localhost
    port: 6379
    database: 1
    password:


