management:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 42.121.255.254
    port: 3306
    database: MS
    username: root
    password: guet123
  redis:
    host: 42.121.255.254
    port: 6379
    database: 1
    password: Redis@Pass123


